language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
sudo: true
# configure environment
before_script:
  - "sudo make configure"
# run Java unit tests
script:
  - "make build"
  - "make check"
# after tests, create package
after_script:
  - "sudo make deb"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
