language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
# configure environment
before_script:
  - "sudo make configure"
# run Java unit tests
script:
  - "make build"
  - "make tests"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
