language: java
jdk:
  - oraclejdk6
  - openjdk6
# configure environment
before_script:
  - "make configure"
# run Java unit tests
script:
  - "make build"
  - "make tests"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
