language: java
jdk:
  - oraclejdk8
  - openjdk8
# configure environment
before_script:
  - "sudo make configure"
# run Java unit tests
script:
  - "make build"
  - "make tests"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
