language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
# install dependencies
#install:
#  - "sudo apt-get install oracle-java6-installer"
# run Java unit tests
script:
  - "make build"
  - "make test"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
