language: java
jdk:
  - "1.6"
# install dependencies
install:
  - "sudo apt-get install oracle-java6-installer"
# run Java unit tests
script:
  - "make build"
  - "java -cp src:build:media:script:lib/commons-io-1.2.jar:lib/log4j-1.2.17.jar:lib/hamcrest-core-1.3.jar:lib/junit-4.12.jar org.junit.runner.JUnitCore com.github.unixpackage.data.ArgumentsTest"
# notify result of build to email address
notifications:
  email:
    - cfermart@gmail.com
